name: thedartpackage
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #base project
  get: 3.26.0
  dio: 3.0.10
  intl: 0.17.0
  uni_links: 0.4.0
  lottie: ^1.0.1

  #Animation
  animate_do: ^2.0.0
  simple_animations: ^3.0.2

  #UI
  carousel_slider: ^3.0.0
  flutter_spinkit: ^5.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/
    - assets/logo/

flutter_intl:
  enabled: true
